### ISSUE TITLE
SetLowLevelPIDs block fails to load the provided configuration

### ISSUE THREAD

**Issue by diegoferigo** [robotology/wb-toolbox#72]
I changed the name of the class containing the configuration to `WBToolbox.PIDConfiguration`, but the `Initialization` function of the mask still uses the old name. It should be renamed.

As a temporary workaround, manually creating the object that the blocks expects works:

```matlab
myPIDConfig = WBToolbox.PIDConfiguration();
% ... Add WBToolbox.PID content
WBTPIDConfigStruct = myPIDConfig.getSimulinkParameters();
```

cc @vibhoraggarwal

**Comment by diegoferigo** [comment]
Fixed by #74.

**Comment by vibhoraggarwal** [comment]
@diegoferigo When I tried to input the PID values using:
`pids = WBToolbox.PIDConfiguration;`
`pids.addPID(WBToolbox.PID('l_hip_pitch', -0.62, 0, 0));`

I get the following error:
![pids](https://user-images.githubusercontent.com/19661841/40620656-e9458ae2-6299-11e8-8eea-220ebf7ca11b.png)

**Comment by diegoferigo** [comment]
@vibhoraggarwal Handling apices in masks is a pain, there was an error which is now fixed in the Simulink Library commit of PR #118. Let me know if it works fine.

**Comment by vibhoraggarwal** [comment]
I tried to use the `set Low Level PIDs` block. It still does not work, and gives me the error, as appended at the end of this comment.
Although, this is the same type of error which was overcome by using a trick mentioned on the [first comment of this thread](https://github.com/robotology/wb-toolbox/issues/72#issue-294709437); but, when I use that now, Matlab also gets stuck.

```Invalid setting in 'SquareTorque2016b/DataCollectin/T/Set LowLevel PIDs1/S-Function' for parameter 'WBTPIDConfigStruct'.
Caused by:
Error evaluating parameter 'WBTPIDConfigStruct' in 'SquareTorque2016b/DataCollectin/T/Set LowLevel PIDs1/S-Function'
Undefined function or variable 'WBTPIDConfigStruct'.

**Comment by diegoferigo** [comment]
PR https://github.com/robotology/wb-toolbox/pull/135 introduced a ne block for setting PIDs with a new logic. Closing.
